
#include "xparameters.h"
#include "basis_io_picozed7030_based_processor_board.h"


// Gate Driver Interfaces

#define DRIVER_1_BASEADDR							XPAR_CONVERTER_1_DRIVER_INTERFACE_BASEADDR
#define DRIVER_2_BASEADDR							XPAR_CONVERTER_2_DRIVER_INTERFACE_BASEADDR


#define DRIVER_1_NO_OF_FPGA_DIS_IN_SIG  			XPAR_CONVERTER_1_DRIVER_INTERFACE_NUMBER_OF_DISABLE_IN_SIGNALS
#define DRIVER_2_NO_OF_FPGA_DIS_IN_SIG  			XPAR_CONVERTER_2_DRIVER_INTERFACE_NUMBER_OF_DISABLE_IN_SIGNALS

//PWM Interfaces
//--------------

#define PWM_1_CARRIER_COUNTER_FRACTIONAL_BITS   	XPAR_CONVERTER_1_PWM_CARRIER_COUNTER_FRACTIONAL_BITS
#define PWM_1_NO_OF_CHANNELS 						XPAR_CONVERTER_1_PWM_NUMBER_OF_CHANNELS
#define PWM_1_BASEADDR								XPAR_CONVERTER_1_PWM_BASEADDR

#define PWM_2_CARRIER_COUNTER_FRACTIONAL_BITS   	XPAR_CONVERTER_2_PWM_CARRIER_COUNTER_FRACTIONAL_BITS
#define PWM_2_NO_OF_CHANNELS 						XPAR_CONVERTER_2_PWM_NUMBER_OF_CHANNELS
#define PWM_2_BASEADDR								XPAR_CONVERTER_2_PWM_BASEADDR

//Trigger block Interfaces
//-------------------------

#define TRIPP_1_BASEADDR   							XPAR_CONVERTER_1_TRIPPING_BASEADDR
#define TRIPP_1_NO_OF_CH   							XPAR_CONVERTER_1_TRIPPING_NUMBER_OF_CHANNELS
#define TRIPP_1_COMP_PER_CH   						XPAR_CONVERTER_1_TRIPPING_NUMBER_OF_COMPARATORS

#define TRIPP_2_BASEADDR   							XPAR_CONVERTER_2_TRIPPING_BASEADDR
#define TRIPP_2_NO_OF_CH   							XPAR_CONVERTER_2_TRIPPING_NUMBER_OF_CHANNELS
#define TRIPP_2_COMP_PER_CH   						XPAR_CONVERTER_2_TRIPPING_NUMBER_OF_COMPARATORS


//Hysteresis Controller Interfaces
//---------------------------------

#define HYSTERESIS_CON_1_BASEADDR   				XPAR_CONVERTER_1_HYSTERESIS_CONTROL_BASEADDR
#define HYSTERESIS_CON_2_BASEADDR   				XPAR_CONVERTER_2_HYSTERESIS_CONTROL_BASEADDR




// Low pass AD-filter block Interfaces
//-------------------------------------

#define CONVERTER_1_AD_FILTER_BASEADDR   			XPAR_CONVERTER_1_AD_FILTER_BLOCK_BASEADDR
#define CONVERTER_1_AD_FILTER_MODE     			    XPAR_CONVERTER_1_AD_FILTER_BLOCK_OPERATION_MODE
#define CONVERTER_1_AD_FILTER_NUMBER_OF_CHANNELS   	XPAR_CONVERTER_1_AD_FILTER_BLOCK_NUMBER_OF_CHANNELS
#define CONVERTER_1_AD_FILTER_IN_WIDTH   			XPAR_CONVERTER_1_AD_FILTER_BLOCK_SIGNAL_IN_WIDTH
#define CONVERTER_1_AD_FILTER_OUT_WIDTH     		XPAR_CONVERTER_1_AD_FILTER_BLOCK_SIGNAL_OUT_WIDTH
#define CONVERTER_1_AD_FILTER_MULTIPLIER_WIDTH   	XPAR_CONVERTER_1_AD_FILTER_BLOCK_MULTIPLIER_WIDTH
#define CONVERTER_1_AD_FILTER_ADDITIONAL_BITS   	XPAR_CONVERTER_1_AD_FILTER_BLOCK_ACCUMULATOR_ADDITIONAL_BITS
#define CONVERTER_1_AD_FILTER_FRACTIONAL_BITS   	XPAR_CONVERTER_1_AD_FILTER_BLOCK_INPUT_FRACTIONAL_BITS

#define CONVERTER_2_AD_FILTER_BASEADDR   			XPAR_CONVERTER_2_AD_FILTER_BLOCK_BASEADDR
#define CONVERTER_2_AD_FILTER_MODE     			    XPAR_CONVERTER_2_AD_FILTER_BLOCK_OPERATION_MODE
#define CONVERTER_2_AD_FILTER_NUMBER_OF_CHANNELS   	XPAR_CONVERTER_2_AD_FILTER_BLOCK_NUMBER_OF_CHANNELS
#define CONVERTER_2_AD_FILTER_IN_WIDTH   			XPAR_CONVERTER_2_AD_FILTER_BLOCK_SIGNAL_IN_WIDTH
#define CONVERTER_2_AD_FILTER_OUT_WIDTH     		XPAR_CONVERTER_2_AD_FILTER_BLOCK_SIGNAL_OUT_WIDTH
#define CONVERTER_2_AD_FILTER_MULTIPLIER_WIDTH   	XPAR_CONVERTER_2_AD_FILTER_BLOCK_MULTIPLIER_WIDTH
#define CONVERTER_2_AD_FILTER_ADDITIONAL_BITS   	XPAR_CONVERTER_2_AD_FILTER_BLOCK_ACCUMULATOR_ADDITIONAL_BITS
#define CONVERTER_2_AD_FILTER_FRACTIONAL_BITS   	XPAR_CONVERTER_2_AD_FILTER_BLOCK_INPUT_FRACTIONAL_BITS


// Moving Average filter block Interfaces
//-------------------------------------

#define CONVERTER_1_MA_FILTER_BASEADDR   			XPAR_CONVERTER_1_MOVING_INTEGRAL_BASEADDR
#define CONVERTER_1_MA_FILTER_MODE     			    XPAR_CONVERTER_1_MOVING_INTEGRAL_OPERATION_MODE
#define CONVERTER_1_MA_FILTER_NUMBER_OF_CHANNELS   	XPAR_CONVERTER_1_MOVING_INTEGRAL_NUMBER_OF_CHANNELS
#define CONVERTER_1_MA_FILTER_IN_WIDTH   			XPAR_CONVERTER_1_MOVING_INTEGRAL_SIGNAL_IN_WIDTH
#define CONVERTER_1_MA_FILTER_OUT_WIDTH     		XPAR_CONVERTER_1_MOVING_INTEGRAL_SIGNAL_OUT_WIDTH
#define CONVERTER_1_MA_FILTER_MULTIPLIER_WIDTH   	XPAR_CONVERTER_1_MOVING_INTEGRAL_MULTIPLIER_WIDTH
#define CONVERTER_1_MA_FILTER_ADDITIONAL_BITS   	XPAR_CONVERTER_1_MOVING_INTEGRAL_ACCUMULATOR_ADDITIONAL_BITS
#define CONVERTER_1_MA_FILTER_FRACTIONAL_BITS   	XPAR_CONVERTER_1_MOVING_INTEGRAL_INPUT_FRACTIONAL_BITS

#define CONVERTER_2_MA_FILTER_BASEADDR   			XPAR_CONVERTER_2_MOVING_INTEGRAL_BASEADDR
#define CONVERTER_2_MA_FILTER_MODE     			    XPAR_CONVERTER_1_MOVING_INTEGRAL_OPERATION_MODE
#define CONVERTER_2_MA_FILTER_NUMBER_OF_CHANNELS   	XPAR_CONVERTER_1_MOVING_INTEGRAL_NUMBER_OF_CHANNELS
#define CONVERTER_2_MA_FILTER_IN_WIDTH   			XPAR_CONVERTER_1_MOVING_INTEGRAL_SIGNAL_IN_WIDTH
#define CONVERTER_2_MA_FILTER_OUT_WIDTH     		XPAR_CONVERTER_1_MOVING_INTEGRAL_SIGNAL_OUT_WIDTH
#define CONVERTER_2_MA_FILTER_MULTIPLIER_WIDTH   	XPAR_CONVERTER_1_MOVING_INTEGRAL_MULTIPLIER_WIDTH
#define CONVERTER_2_MA_FILTER_ADDITIONAL_BITS   	XPAR_CONVERTER_1_MOVING_INTEGRAL_ACCUMULATOR_ADDITIONAL_BITS
#define CONVERTER_2_MA_FILTER_FRACTIONAL_BITS   	XPAR_CONVERTER_1_MOVING_INTEGRAL_INPUT_FRACTIONAL_BITS

// Synchronized Sampled Output register
//----------------------------------------

#define CONVERTER_1_SYNCH_SAMPLED_BASEADDR   		XPAR_CONVERTER_1_SYNCH_SAMPLING_REG_BASEADDR
#define CONVERTER_2_SYNCH_SAMPLED_BASEADDR   		XPAR_CONVERTER_2_SYNCH_SAMPLING_REG_BASEADDR



// Moving Average Sampled Output register
//----------------------------------------

#define CONVERTER_1_MA_SAMPLED_BASEADDR   			XPAR_CONVERTER_1_MOVING_INTEGRAL_REG_BASEADDR
#define CONVERTER_2_MA_SAMPLED_BASEADDR   			XPAR_CONVERTER_2_MOVING_INTEGRAL_REG_BASEADDR




