
 PARAMETER VERSION = 2.2.0


BEGIN OS
 PARAMETER OS_NAME = standalone
 PARAMETER OS_VER = 7.0
 PARAMETER PROC_INSTANCE = ps7_cortexa9_1
END


BEGIN PROCESSOR
 PARAMETER DRIVER_NAME = cpu_cortexa9
 PARAMETER DRIVER_VER = 2.7
 PARAMETER HW_INSTANCE = ps7_cortexa9_1
 PARAMETER extra_compiler_flags = -DUSE_AMP=1 -mcpu=cortex-a9 -mfpu=vfpv3 -mfloat-abi=hard -nostartfiles -g -Wall -Wextra
END


BEGIN DRIVER
 PARAMETER DRIVER_NAME = ad_converter_serial_receiver
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = ad_converter
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 4.4
 PARAMETER HW_INSTANCE = axi_gpio_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = filter_block
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = converter_1_AD_filter_block
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = register_array
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = converter_1_CurrentRef
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = comparator_limiter_block
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = converter_1_Hysteresis_control
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = filter_block
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = converter_1_Moving_integral
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = comparator_limiter_block
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = converter_1_Tripping
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = blankingtimecorr
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = converter_1_blankingtimecorr_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = driver_interface
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = converter_1_driver_interface
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = register_array
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = converter_1_moving_integral_reg
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = pulse_width_modulator
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = converter_1_pwm
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = switching_event_counter
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = converter_1_switching_event_counter
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = register_array
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = converter_1_synch_sampling_reg
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = filter_block
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = converter_2_AD_filter_block
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = register_array
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = converter_2_CurrentRef
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = comparator_limiter_block
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = converter_2_Hysteresis_control
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = filter_block
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = converter_2_Moving_integral
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = comparator_limiter_block
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = converter_2_Tripping
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = blankingtimecorr
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = converter_2_blankingtimecorr_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = driver_interface
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = converter_2_driver_interface
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = register_array
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = converter_2_moving_integral_reg
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = pulse_width_modulator
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = converter_2_pwm
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = switching_event_counter
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = converter_2_switching_event_counter
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = register_array
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = converter_2_synch_sampling_reg
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = da_converter_interface
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = da_converter
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = emu_dc
 PARAMETER DRIVER_VER = 5.16
 PARAMETER HW_INSTANCE = emu_dc_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = incremental_encoder_interface
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = encoder_interface
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = multiplexer
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = multiplexer_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_afi_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_afi_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_afi_2
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_afi_3
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = canps
 PARAMETER DRIVER_VER = 3.2
 PARAMETER HW_INSTANCE = ps7_can_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = coresightps_dcc
 PARAMETER DRIVER_VER = 1.5
 PARAMETER HW_INSTANCE = ps7_coresight_comp_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = ddrps
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = ps7_ddr_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_ddrc_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = devcfg
 PARAMETER DRIVER_VER = 3.5
 PARAMETER HW_INSTANCE = ps7_dev_cfg_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = dmaps
 PARAMETER DRIVER_VER = 2.4
 PARAMETER HW_INSTANCE = ps7_dma_ns
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = dmaps
 PARAMETER DRIVER_VER = 2.4
 PARAMETER HW_INSTANCE = ps7_dma_s
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = emacps
 PARAMETER DRIVER_VER = 3.9
 PARAMETER HW_INSTANCE = ps7_ethernet_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_globaltimer_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpiops
 PARAMETER DRIVER_VER = 3.5
 PARAMETER HW_INSTANCE = ps7_gpio_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_gpv_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_intc_dist_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_iop_bus_config_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_l2cachec_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_ocmc_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_pl310_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_pmu_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = qspips
 PARAMETER DRIVER_VER = 3.6
 PARAMETER HW_INSTANCE = ps7_qspi_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_qspi_linear_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_ram_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_ram_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_scuc_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = scugic
 PARAMETER DRIVER_VER = 4.0
 PARAMETER HW_INSTANCE = ps7_scugic_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = scutimer
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = ps7_scutimer_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = scuwdt
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = ps7_scuwdt_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = sdps
 PARAMETER DRIVER_VER = 3.7
 PARAMETER HW_INSTANCE = ps7_sd_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ps7_slcr_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = spips
 PARAMETER DRIVER_VER = 3.2
 PARAMETER HW_INSTANCE = ps7_spi_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = spips
 PARAMETER DRIVER_VER = 3.2
 PARAMETER HW_INSTANCE = ps7_spi_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = ttcps
 PARAMETER DRIVER_VER = 3.9
 PARAMETER HW_INSTANCE = ps7_ttc_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartps
 PARAMETER DRIVER_VER = 3.7
 PARAMETER HW_INSTANCE = ps7_uart_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = usbps
 PARAMETER DRIVER_VER = 2.4
 PARAMETER HW_INSTANCE = ps7_usb_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = xadcps
 PARAMETER DRIVER_VER = 2.3
 PARAMETER HW_INSTANCE = ps7_xadc_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = register_array
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = register_emu_input
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = register_array
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = register_emu_out
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = register_array
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = register_mux_out
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = register_array
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = relay
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 4.4
 PARAMETER HW_INSTANCE = signal_in
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 4.4
 PARAMETER HW_INSTANCE = testled
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = sysmon
 PARAMETER DRIVER_VER = 7.5
 PARAMETER HW_INSTANCE = xadc_wiz_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = ENDAT22_S_1
END


