#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

/* Definition for CPU ID */
#define XPAR_CPU_ID 1U

/* Definitions for peripheral PS7_CORTEXA9_1 */
#define XPAR_PS7_CORTEXA9_1_CPU_CLK_FREQ_HZ 666666687


/******************************************************************/

/* Canonical definitions for peripheral PS7_CORTEXA9_1 */
#define XPAR_CPU_CORTEXA9_0_CPU_CLK_FREQ_HZ 666666687


/******************************************************************/

#include "xparameters_ps.h"


/******************************************************************/

/* Platform specific definitions */
#define PLATFORM_ZYNQ
 
/* Definitions for sleep timer configuration */
#define XSLEEP_TIMER_IS_DEFAULT_TIMER
 
 
/******************************************************************/
/* Definitions for driver AD_CONVERTER_SERIAL_RECEIVER */
#define XPAR_AD_CONVERTER_SERIAL_RECEIVER_NUM_INSTANCES 1

/* Definitions for peripheral AD_CONVERTER */
#define XPAR_AD_CONVERTER_DEVICE_ID 0
#define XPAR_AD_CONVERTER_BASEADDR 0x43C00000
#define XPAR_AD_CONVERTER_HIGHADDR 0x43C0FFFF
#define XPAR_AD_CONVERTER_OUTPUT_SIGNAL_CLOCK_DOMAIN_SELECTOR "00000000"
#define XPAR_AD_CONVERTER_INIT_DELAY_COUNTER_START_VALUE 10
#define XPAR_AD_CONVERTER_CONFIG_REG_DEFAULT_VALUE 0
#define XPAR_AD_CONVERTER_INVERT_OPUTPUT_SIGNAL "00000000"
#define XPAR_AD_CONVERTER_USE_OFFSET_COMPENSATION "1"
#define XPAR_AD_CONVERTER_AD_CLOCK_IOBDELAY_VALUE 7
#define XPAR_AD_CONVERTER_AD_SIGNAL_IOBDELAY_VALUE 22
#define XPAR_AD_CONVERTER_USE_INTERNAL_DELAYCTRL "1"
#define XPAR_AD_CONVERTER_DOWNSAMPLING_FACTOR_WIDTH 0
#define XPAR_AD_CONVERTER_NUMBER_OF_CHANNELS 8
#define XPAR_AD_CONVERTER_WIDTH_OUT 13


/******************************************************************/

/* Definitions for driver BLANKINGTIMECORR */
#define XPAR_BLANKINGTIMECORR_NUM_INSTANCES 2

/* Definitions for peripheral CONVERTER_1_BLANKINGTIMECORR_0 */
#define XPAR_CONVERTER_1_BLANKINGTIMECORR_0_DEVICE_ID 0
#define XPAR_CONVERTER_1_BLANKINGTIMECORR_0_BLANKINGTIMECORR_S_AXI_BASEADDR 0x43D70000
#define XPAR_CONVERTER_1_BLANKINGTIMECORR_0_BLANKINGTIMECORR_S_AXI_HIGHADDR 0x43D7FFFF


/* Definitions for peripheral CONVERTER_2_BLANKINGTIMECORR_0 */
#define XPAR_CONVERTER_2_BLANKINGTIMECORR_0_DEVICE_ID 1
#define XPAR_CONVERTER_2_BLANKINGTIMECORR_0_BLANKINGTIMECORR_S_AXI_BASEADDR 0x43D80000
#define XPAR_CONVERTER_2_BLANKINGTIMECORR_0_BLANKINGTIMECORR_S_AXI_HIGHADDR 0x43D8FFFF


/******************************************************************/

/* Canonical definitions for peripheral CONVERTER_1_BLANKINGTIMECORR_0 */
#define XPAR_BLANKINGTIMECORR_0_DEVICE_ID XPAR_CONVERTER_1_BLANKINGTIMECORR_0_DEVICE_ID
#define XPAR_BLANKINGTIMECORR_0_BLANKINGTIMECORR_S_AXI_BASEADDR 0x43D70000
#define XPAR_BLANKINGTIMECORR_0_BLANKINGTIMECORR_S_AXI_HIGHADDR 0x43D7FFFF

/* Canonical definitions for peripheral CONVERTER_2_BLANKINGTIMECORR_0 */
#define XPAR_BLANKINGTIMECORR_1_DEVICE_ID XPAR_CONVERTER_2_BLANKINGTIMECORR_0_DEVICE_ID
#define XPAR_BLANKINGTIMECORR_1_BLANKINGTIMECORR_S_AXI_BASEADDR 0x43D80000
#define XPAR_BLANKINGTIMECORR_1_BLANKINGTIMECORR_S_AXI_HIGHADDR 0x43D8FFFF


/******************************************************************/

/* Definitions for driver CANPS */
#define XPAR_XCANPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_CAN_1 */
#define XPAR_PS7_CAN_1_DEVICE_ID 0
#define XPAR_PS7_CAN_1_BASEADDR 0xE0009000
#define XPAR_PS7_CAN_1_HIGHADDR 0xE0009FFF
#define XPAR_PS7_CAN_1_CAN_CLK_FREQ_HZ 100000000


/******************************************************************/

/* Canonical definitions for peripheral PS7_CAN_1 */
#define XPAR_XCANPS_0_DEVICE_ID XPAR_PS7_CAN_1_DEVICE_ID
#define XPAR_XCANPS_0_BASEADDR 0xE0009000
#define XPAR_XCANPS_0_HIGHADDR 0xE0009FFF
#define XPAR_XCANPS_0_CAN_CLK_FREQ_HZ 100000000


/******************************************************************/

/* Definitions for driver COMPARATOR_LIMITER_BLOCK */
#define XPAR_COMPARATOR_LIMITER_BLOCK_NUM_INSTANCES 4

/* Definitions for peripheral CONVERTER_1_HYSTERESIS_CONTROL */
#define XPAR_CONVERTER_1_HYSTERESIS_CONTROL_DEVICE_ID 0
#define XPAR_CONVERTER_1_HYSTERESIS_CONTROL_BASEADDR 0x43D50000
#define XPAR_CONVERTER_1_HYSTERESIS_CONTROL_HIGHADDR 0x43D5FFFF
#define XPAR_CONVERTER_1_HYSTERESIS_CONTROL_WIDTH_IN 14
#define XPAR_CONVERTER_1_HYSTERESIS_CONTROL_WIDTH_OUT 13
#define XPAR_CONVERTER_1_HYSTERESIS_CONTROL_NUMBER_OF_CHANNELS 3
#define XPAR_CONVERTER_1_HYSTERESIS_CONTROL_NUMBER_OF_COMPARATORS 2
#define XPAR_CONVERTER_1_HYSTERESIS_CONTROL_FLIPFLOP_DEFAULT_VALUE "0"
#define XPAR_CONVERTER_1_HYSTERESIS_CONTROL_COMPARATOR_FUNCTION_GREATER_THAN 0x00000002
#define XPAR_CONVERTER_1_HYSTERESIS_CONTROL_COMPARATOR_FUNCTION_LESS_THAN 0x00000001
#define XPAR_CONVERTER_1_HYSTERESIS_CONTROL_COMPARATOR_FUNCTION_EQUAL 0x00000002
#define XPAR_CONVERTER_1_HYSTERESIS_CONTROL_REGISTER_SET_MASK 0x00000002
#define XPAR_CONVERTER_1_HYSTERESIS_CONTROL_REGISTER_CLEAR_MASK 0x00000001
#define XPAR_CONVERTER_1_HYSTERESIS_CONTROL_READ_CLIPPED_SIGNALS 0
#define XPAR_CONVERTER_1_HYSTERESIS_CONTROL_READ_REFERENCES 1
#define XPAR_CONVERTER_1_HYSTERESIS_CONTROL_REFERENCE_SELECTOR 0
#define XPAR_CONVERTER_1_HYSTERESIS_CONTROL_SEPARATE_REFERENCES 0


/* Definitions for peripheral CONVERTER_1_TRIPPING */
#define XPAR_CONVERTER_1_TRIPPING_DEVICE_ID 1
#define XPAR_CONVERTER_1_TRIPPING_BASEADDR 0x43D90000
#define XPAR_CONVERTER_1_TRIPPING_HIGHADDR 0x43D9FFFF
#define XPAR_CONVERTER_1_TRIPPING_WIDTH_IN 13
#define XPAR_CONVERTER_1_TRIPPING_WIDTH_OUT 13
#define XPAR_CONVERTER_1_TRIPPING_NUMBER_OF_CHANNELS 4
#define XPAR_CONVERTER_1_TRIPPING_NUMBER_OF_COMPARATORS 2
#define XPAR_CONVERTER_1_TRIPPING_FLIPFLOP_DEFAULT_VALUE "0"
#define XPAR_CONVERTER_1_TRIPPING_COMPARATOR_FUNCTION_GREATER_THAN 0x00000002
#define XPAR_CONVERTER_1_TRIPPING_COMPARATOR_FUNCTION_LESS_THAN 0x00000001
#define XPAR_CONVERTER_1_TRIPPING_COMPARATOR_FUNCTION_EQUAL 0x00000002
#define XPAR_CONVERTER_1_TRIPPING_REGISTER_SET_MASK 0x00000003
#define XPAR_CONVERTER_1_TRIPPING_REGISTER_CLEAR_MASK 0x00000000
#define XPAR_CONVERTER_1_TRIPPING_READ_CLIPPED_SIGNALS 0
#define XPAR_CONVERTER_1_TRIPPING_READ_REFERENCES 1
#define XPAR_CONVERTER_1_TRIPPING_REFERENCE_SELECTOR 0
#define XPAR_CONVERTER_1_TRIPPING_SEPARATE_REFERENCES 1


/* Definitions for peripheral CONVERTER_2_HYSTERESIS_CONTROL */
#define XPAR_CONVERTER_2_HYSTERESIS_CONTROL_DEVICE_ID 2
#define XPAR_CONVERTER_2_HYSTERESIS_CONTROL_BASEADDR 0x43CD0000
#define XPAR_CONVERTER_2_HYSTERESIS_CONTROL_HIGHADDR 0x43CDFFFF
#define XPAR_CONVERTER_2_HYSTERESIS_CONTROL_WIDTH_IN 14
#define XPAR_CONVERTER_2_HYSTERESIS_CONTROL_WIDTH_OUT 13
#define XPAR_CONVERTER_2_HYSTERESIS_CONTROL_NUMBER_OF_CHANNELS 3
#define XPAR_CONVERTER_2_HYSTERESIS_CONTROL_NUMBER_OF_COMPARATORS 2
#define XPAR_CONVERTER_2_HYSTERESIS_CONTROL_FLIPFLOP_DEFAULT_VALUE "0"
#define XPAR_CONVERTER_2_HYSTERESIS_CONTROL_COMPARATOR_FUNCTION_GREATER_THAN 0x00000002
#define XPAR_CONVERTER_2_HYSTERESIS_CONTROL_COMPARATOR_FUNCTION_LESS_THAN 0x00000001
#define XPAR_CONVERTER_2_HYSTERESIS_CONTROL_COMPARATOR_FUNCTION_EQUAL 0x00000002
#define XPAR_CONVERTER_2_HYSTERESIS_CONTROL_REGISTER_SET_MASK 0x00000002
#define XPAR_CONVERTER_2_HYSTERESIS_CONTROL_REGISTER_CLEAR_MASK 0x00000001
#define XPAR_CONVERTER_2_HYSTERESIS_CONTROL_READ_CLIPPED_SIGNALS 0
#define XPAR_CONVERTER_2_HYSTERESIS_CONTROL_READ_REFERENCES 1
#define XPAR_CONVERTER_2_HYSTERESIS_CONTROL_REFERENCE_SELECTOR 0
#define XPAR_CONVERTER_2_HYSTERESIS_CONTROL_SEPARATE_REFERENCES 0


/* Definitions for peripheral CONVERTER_2_TRIPPING */
#define XPAR_CONVERTER_2_TRIPPING_DEVICE_ID 3
#define XPAR_CONVERTER_2_TRIPPING_BASEADDR 0x43DA0000
#define XPAR_CONVERTER_2_TRIPPING_HIGHADDR 0x43DAFFFF
#define XPAR_CONVERTER_2_TRIPPING_WIDTH_IN 13
#define XPAR_CONVERTER_2_TRIPPING_WIDTH_OUT 13
#define XPAR_CONVERTER_2_TRIPPING_NUMBER_OF_CHANNELS 4
#define XPAR_CONVERTER_2_TRIPPING_NUMBER_OF_COMPARATORS 2
#define XPAR_CONVERTER_2_TRIPPING_FLIPFLOP_DEFAULT_VALUE "0"
#define XPAR_CONVERTER_2_TRIPPING_COMPARATOR_FUNCTION_GREATER_THAN 0x00000002
#define XPAR_CONVERTER_2_TRIPPING_COMPARATOR_FUNCTION_LESS_THAN 0x00000001
#define XPAR_CONVERTER_2_TRIPPING_COMPARATOR_FUNCTION_EQUAL 0x00000002
#define XPAR_CONVERTER_2_TRIPPING_REGISTER_SET_MASK 0x00000003
#define XPAR_CONVERTER_2_TRIPPING_REGISTER_CLEAR_MASK 0x00000000
#define XPAR_CONVERTER_2_TRIPPING_READ_CLIPPED_SIGNALS 0
#define XPAR_CONVERTER_2_TRIPPING_READ_REFERENCES 1
#define XPAR_CONVERTER_2_TRIPPING_REFERENCE_SELECTOR 0
#define XPAR_CONVERTER_2_TRIPPING_SEPARATE_REFERENCES 1


/******************************************************************/

/* Definitions for driver DA_CONVERTER_INTERFACE */
#define XPAR_DA_CONVERTER_INTERFACE_NUM_INSTANCES 1

/* Definitions for peripheral DA_CONVERTER */
#define XPAR_DA_CONVERTER_DEVICE_ID 0
#define XPAR_DA_CONVERTER_BASEADDR 0x43C10000
#define XPAR_DA_CONVERTER_HIGHADDR 0x43C1FFFF
#define XPAR_DA_CONVERTER_NUMBER_OF_SIGNAL_SOURCES 48
#define XPAR_DA_CONVERTER_WIDTH_IN 16
#define XPAR_DA_CONVERTER_USE_SCALING 1
#define XPAR_DA_CONVERTER_SCALE_SHIFTS 8
#define XPAR_DA_CONVERTER_CONFIG_REG_DEFAULT_VALUE 0x00000000
#define XPAR_DA_CONVERTER_CLOCK_PULSES_CS_LOW 2
#define XPAR_DA_CONVERTER_DA_CONVERTER_WIDTH 12
#define XPAR_DA_CONVERTER_NUMBER_OF_CHANNELS 4


/******************************************************************/


/* Definitions for peripheral PS7_DDR_0 */
#define XPAR_PS7_DDR_0_S_AXI_BASEADDR 0x00100000
#define XPAR_PS7_DDR_0_S_AXI_HIGHADDR 0x3FFFFFFF


/******************************************************************/

/* Definitions for driver DEVCFG */
#define XPAR_XDCFG_NUM_INSTANCES 1U

/* Definitions for peripheral PS7_DEV_CFG_0 */
#define XPAR_PS7_DEV_CFG_0_DEVICE_ID 0U
#define XPAR_PS7_DEV_CFG_0_BASEADDR 0xF8007000U
#define XPAR_PS7_DEV_CFG_0_HIGHADDR 0xF80070FFU


/******************************************************************/

/* Canonical definitions for peripheral PS7_DEV_CFG_0 */
#define XPAR_XDCFG_0_DEVICE_ID XPAR_PS7_DEV_CFG_0_DEVICE_ID
#define XPAR_XDCFG_0_BASEADDR 0xF8007000U
#define XPAR_XDCFG_0_HIGHADDR 0xF80070FFU


/******************************************************************/

/* Definitions for driver DMAPS */
#define XPAR_XDMAPS_NUM_INSTANCES 2

/* Definitions for peripheral PS7_DMA_NS */
#define XPAR_PS7_DMA_NS_DEVICE_ID 0
#define XPAR_PS7_DMA_NS_BASEADDR 0xF8004000
#define XPAR_PS7_DMA_NS_HIGHADDR 0xF8004FFF


/* Definitions for peripheral PS7_DMA_S */
#define XPAR_PS7_DMA_S_DEVICE_ID 1
#define XPAR_PS7_DMA_S_BASEADDR 0xF8003000
#define XPAR_PS7_DMA_S_HIGHADDR 0xF8003FFF


/******************************************************************/

/* Canonical definitions for peripheral PS7_DMA_NS */
#define XPAR_XDMAPS_0_DEVICE_ID XPAR_PS7_DMA_NS_DEVICE_ID
#define XPAR_XDMAPS_0_BASEADDR 0xF8004000
#define XPAR_XDMAPS_0_HIGHADDR 0xF8004FFF

/* Canonical definitions for peripheral PS7_DMA_S */
#define XPAR_XDMAPS_1_DEVICE_ID XPAR_PS7_DMA_S_DEVICE_ID
#define XPAR_XDMAPS_1_BASEADDR 0xF8003000
#define XPAR_XDMAPS_1_HIGHADDR 0xF8003FFF


/******************************************************************/

/* Definitions for driver DRIVER_INTERFACE */
#define XPAR_DRIVER_INTERFACE_NUM_INSTANCES 2

/* Definitions for peripheral CONVERTER_1_DRIVER_INTERFACE */
#define XPAR_CONVERTER_1_DRIVER_INTERFACE_DEVICE_ID 0
#define XPAR_CONVERTER_1_DRIVER_INTERFACE_BASEADDR 0x43C50000
#define XPAR_CONVERTER_1_DRIVER_INTERFACE_HIGHADDR 0x43C5FFFF
#define XPAR_CONVERTER_1_DRIVER_INTERFACE_NUMBER_OF_SIGNAL_SOURCES 2
#define XPAR_CONVERTER_1_DRIVER_INTERFACE_SEPARATE_SIGNALS_FOR_LOWER_DRIVERS 0
#define XPAR_CONVERTER_1_DRIVER_INTERFACE_CONFIG_REG_DEFAULT_VALUE 0x00131313
#define XPAR_CONVERTER_1_DRIVER_INTERFACE_SIGNAL_SOURCE_REG_DEFAULT_VALUE 0x00000000
#define XPAR_CONVERTER_1_DRIVER_INTERFACE_USE_WATCHDOG_TIMER 1
#define XPAR_CONVERTER_1_DRIVER_INTERFACE_PILOT_SIGNAL_BITNR 6
#define XPAR_CONVERTER_1_DRIVER_INTERFACE_NUMBER_OF_DISABLE_IN_SIGNALS 4


/* Definitions for peripheral CONVERTER_2_DRIVER_INTERFACE */
#define XPAR_CONVERTER_2_DRIVER_INTERFACE_DEVICE_ID 1
#define XPAR_CONVERTER_2_DRIVER_INTERFACE_BASEADDR 0x43C60000
#define XPAR_CONVERTER_2_DRIVER_INTERFACE_HIGHADDR 0x43C6FFFF
#define XPAR_CONVERTER_2_DRIVER_INTERFACE_NUMBER_OF_SIGNAL_SOURCES 2
#define XPAR_CONVERTER_2_DRIVER_INTERFACE_SEPARATE_SIGNALS_FOR_LOWER_DRIVERS 0
#define XPAR_CONVERTER_2_DRIVER_INTERFACE_CONFIG_REG_DEFAULT_VALUE 0x00131313
#define XPAR_CONVERTER_2_DRIVER_INTERFACE_SIGNAL_SOURCE_REG_DEFAULT_VALUE 0x00000000
#define XPAR_CONVERTER_2_DRIVER_INTERFACE_USE_WATCHDOG_TIMER 1
#define XPAR_CONVERTER_2_DRIVER_INTERFACE_PILOT_SIGNAL_BITNR 6
#define XPAR_CONVERTER_2_DRIVER_INTERFACE_NUMBER_OF_DISABLE_IN_SIGNALS 4


/******************************************************************/

/* Definitions for driver EMACPS */
#define XPAR_XEMACPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_ETHERNET_0 */
#define XPAR_PS7_ETHERNET_0_DEVICE_ID 0
#define XPAR_PS7_ETHERNET_0_BASEADDR 0xE000B000
#define XPAR_PS7_ETHERNET_0_HIGHADDR 0xE000BFFF
#define XPAR_PS7_ETHERNET_0_ENET_CLK_FREQ_HZ 125000000
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_1000MBPS_DIV0 8
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_1000MBPS_DIV1 1
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_100MBPS_DIV0 8
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_100MBPS_DIV1 5
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_10MBPS_DIV0 8
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_10MBPS_DIV1 50
#define XPAR_PS7_ETHERNET_0_ENET_TSU_CLK_FREQ_HZ 0


/******************************************************************/

#define XPAR_PS7_ETHERNET_0_IS_CACHE_COHERENT 0
#define XPAR_XEMACPS_0_IS_CACHE_COHERENT 0
/* Canonical definitions for peripheral PS7_ETHERNET_0 */
#define XPAR_XEMACPS_0_DEVICE_ID XPAR_PS7_ETHERNET_0_DEVICE_ID
#define XPAR_XEMACPS_0_BASEADDR 0xE000B000
#define XPAR_XEMACPS_0_HIGHADDR 0xE000BFFF
#define XPAR_XEMACPS_0_ENET_CLK_FREQ_HZ 125000000
#define XPAR_XEMACPS_0_ENET_SLCR_1000Mbps_DIV0 8
#define XPAR_XEMACPS_0_ENET_SLCR_1000Mbps_DIV1 1
#define XPAR_XEMACPS_0_ENET_SLCR_100Mbps_DIV0 8
#define XPAR_XEMACPS_0_ENET_SLCR_100Mbps_DIV1 5
#define XPAR_XEMACPS_0_ENET_SLCR_10Mbps_DIV0 8
#define XPAR_XEMACPS_0_ENET_SLCR_10Mbps_DIV1 50
#define XPAR_XEMACPS_0_ENET_TSU_CLK_FREQ_HZ 0


/******************************************************************/

/* Definitions for driver EMU_DC */
#define XPAR_EMU_DC_NUM_INSTANCES 1

/* Definitions for peripheral EMU_DC_0 */
#define XPAR_EMU_DC_0_DEVICE_ID 0
#define XPAR_EMU_DC_0_EMU_DC_S_AXI_BASEADDR 0x43DC0000
#define XPAR_EMU_DC_0_EMU_DC_S_AXI_HIGHADDR 0x43DCFFFF


/******************************************************************/


/******************************************************************/

/* Definitions for driver FILTER_BLOCK */
#define XPAR_FILTER_BLOCK_NUM_INSTANCES 4

/* Definitions for peripheral CONVERTER_1_AD_FILTER_BLOCK */
#define XPAR_CONVERTER_1_AD_FILTER_BLOCK_DEVICE_ID 0
#define XPAR_CONVERTER_1_AD_FILTER_BLOCK_BASEADDR 0x43C40000
#define XPAR_CONVERTER_1_AD_FILTER_BLOCK_HIGHADDR 0x43C4FFFF
#define XPAR_CONVERTER_1_AD_FILTER_BLOCK_OPERATION_MODE 1
#define XPAR_CONVERTER_1_AD_FILTER_BLOCK_NUMBER_OF_CHANNELS 4
#define XPAR_CONVERTER_1_AD_FILTER_BLOCK_SIGNAL_IN_WIDTH 13
#define XPAR_CONVERTER_1_AD_FILTER_BLOCK_SIGNAL_OUT_WIDTH 13
#define XPAR_CONVERTER_1_AD_FILTER_BLOCK_MULTIPLIER_WIDTH 25
#define XPAR_CONVERTER_1_AD_FILTER_BLOCK_ACCUMULATOR_ADDITIONAL_BITS 0
#define XPAR_CONVERTER_1_AD_FILTER_BLOCK_INPUT_FRACTIONAL_BITS 0
#define XPAR_CONVERTER_1_AD_FILTER_BLOCK_INPUT_SOURCE_CONFIG 2
#define XPAR_CONVERTER_1_AD_FILTER_BLOCK_SCALING 1
#define XPAR_CONVERTER_1_AD_FILTER_BLOCK_COMMON_PARAMETERS 0
#define XPAR_CONVERTER_1_AD_FILTER_BLOCK_ACCUMULATOR_WRITE 1


/* Definitions for peripheral CONVERTER_1_MOVING_INTEGRAL */
#define XPAR_CONVERTER_1_MOVING_INTEGRAL_DEVICE_ID 1
#define XPAR_CONVERTER_1_MOVING_INTEGRAL_BASEADDR 0x43D30000
#define XPAR_CONVERTER_1_MOVING_INTEGRAL_HIGHADDR 0x43D3FFFF
#define XPAR_CONVERTER_1_MOVING_INTEGRAL_OPERATION_MODE 0
#define XPAR_CONVERTER_1_MOVING_INTEGRAL_NUMBER_OF_CHANNELS 8
#define XPAR_CONVERTER_1_MOVING_INTEGRAL_SIGNAL_IN_WIDTH 13
#define XPAR_CONVERTER_1_MOVING_INTEGRAL_SIGNAL_OUT_WIDTH 24
#define XPAR_CONVERTER_1_MOVING_INTEGRAL_MULTIPLIER_WIDTH 25
#define XPAR_CONVERTER_1_MOVING_INTEGRAL_ACCUMULATOR_ADDITIONAL_BITS 0
#define XPAR_CONVERTER_1_MOVING_INTEGRAL_INPUT_FRACTIONAL_BITS 0
#define XPAR_CONVERTER_1_MOVING_INTEGRAL_INPUT_SOURCE_CONFIG 2
#define XPAR_CONVERTER_1_MOVING_INTEGRAL_SCALING 1
#define XPAR_CONVERTER_1_MOVING_INTEGRAL_COMMON_PARAMETERS 0
#define XPAR_CONVERTER_1_MOVING_INTEGRAL_ACCUMULATOR_WRITE 1


/* Definitions for peripheral CONVERTER_2_AD_FILTER_BLOCK */
#define XPAR_CONVERTER_2_AD_FILTER_BLOCK_DEVICE_ID 2
#define XPAR_CONVERTER_2_AD_FILTER_BLOCK_BASEADDR 0x43C20000
#define XPAR_CONVERTER_2_AD_FILTER_BLOCK_HIGHADDR 0x43C2FFFF
#define XPAR_CONVERTER_2_AD_FILTER_BLOCK_OPERATION_MODE 1
#define XPAR_CONVERTER_2_AD_FILTER_BLOCK_NUMBER_OF_CHANNELS 4
#define XPAR_CONVERTER_2_AD_FILTER_BLOCK_SIGNAL_IN_WIDTH 13
#define XPAR_CONVERTER_2_AD_FILTER_BLOCK_SIGNAL_OUT_WIDTH 13
#define XPAR_CONVERTER_2_AD_FILTER_BLOCK_MULTIPLIER_WIDTH 25
#define XPAR_CONVERTER_2_AD_FILTER_BLOCK_ACCUMULATOR_ADDITIONAL_BITS 0
#define XPAR_CONVERTER_2_AD_FILTER_BLOCK_INPUT_FRACTIONAL_BITS 0
#define XPAR_CONVERTER_2_AD_FILTER_BLOCK_INPUT_SOURCE_CONFIG 2
#define XPAR_CONVERTER_2_AD_FILTER_BLOCK_SCALING 1
#define XPAR_CONVERTER_2_AD_FILTER_BLOCK_COMMON_PARAMETERS 0
#define XPAR_CONVERTER_2_AD_FILTER_BLOCK_ACCUMULATOR_WRITE 1


/* Definitions for peripheral CONVERTER_2_MOVING_INTEGRAL */
#define XPAR_CONVERTER_2_MOVING_INTEGRAL_DEVICE_ID 3
#define XPAR_CONVERTER_2_MOVING_INTEGRAL_BASEADDR 0x43CB0000
#define XPAR_CONVERTER_2_MOVING_INTEGRAL_HIGHADDR 0x43CBFFFF
#define XPAR_CONVERTER_2_MOVING_INTEGRAL_OPERATION_MODE 0
#define XPAR_CONVERTER_2_MOVING_INTEGRAL_NUMBER_OF_CHANNELS 8
#define XPAR_CONVERTER_2_MOVING_INTEGRAL_SIGNAL_IN_WIDTH 13
#define XPAR_CONVERTER_2_MOVING_INTEGRAL_SIGNAL_OUT_WIDTH 24
#define XPAR_CONVERTER_2_MOVING_INTEGRAL_MULTIPLIER_WIDTH 25
#define XPAR_CONVERTER_2_MOVING_INTEGRAL_ACCUMULATOR_ADDITIONAL_BITS 0
#define XPAR_CONVERTER_2_MOVING_INTEGRAL_INPUT_FRACTIONAL_BITS 0
#define XPAR_CONVERTER_2_MOVING_INTEGRAL_INPUT_SOURCE_CONFIG 2
#define XPAR_CONVERTER_2_MOVING_INTEGRAL_SCALING 1
#define XPAR_CONVERTER_2_MOVING_INTEGRAL_COMMON_PARAMETERS 0
#define XPAR_CONVERTER_2_MOVING_INTEGRAL_ACCUMULATOR_WRITE 1


/******************************************************************/


/* Definitions for peripheral PS7_AFI_0 */
#define XPAR_PS7_AFI_0_S_AXI_BASEADDR 0xF8008000
#define XPAR_PS7_AFI_0_S_AXI_HIGHADDR 0xF8008FFF


/* Definitions for peripheral PS7_AFI_1 */
#define XPAR_PS7_AFI_1_S_AXI_BASEADDR 0xF8009000
#define XPAR_PS7_AFI_1_S_AXI_HIGHADDR 0xF8009FFF


/* Definitions for peripheral PS7_AFI_2 */
#define XPAR_PS7_AFI_2_S_AXI_BASEADDR 0xF800A000
#define XPAR_PS7_AFI_2_S_AXI_HIGHADDR 0xF800AFFF


/* Definitions for peripheral PS7_AFI_3 */
#define XPAR_PS7_AFI_3_S_AXI_BASEADDR 0xF800B000
#define XPAR_PS7_AFI_3_S_AXI_HIGHADDR 0xF800BFFF


/* Definitions for peripheral PS7_DDRC_0 */
#define XPAR_PS7_DDRC_0_S_AXI_BASEADDR 0xF8006000
#define XPAR_PS7_DDRC_0_S_AXI_HIGHADDR 0xF8006FFF


/* Definitions for peripheral PS7_GLOBALTIMER_0 */
#define XPAR_PS7_GLOBALTIMER_0_S_AXI_BASEADDR 0xF8F00200
#define XPAR_PS7_GLOBALTIMER_0_S_AXI_HIGHADDR 0xF8F002FF


/* Definitions for peripheral PS7_GPV_0 */
#define XPAR_PS7_GPV_0_S_AXI_BASEADDR 0xF8900000
#define XPAR_PS7_GPV_0_S_AXI_HIGHADDR 0xF89FFFFF


/* Definitions for peripheral PS7_INTC_DIST_0 */
#define XPAR_PS7_INTC_DIST_0_S_AXI_BASEADDR 0xF8F01000
#define XPAR_PS7_INTC_DIST_0_S_AXI_HIGHADDR 0xF8F01FFF


/* Definitions for peripheral PS7_IOP_BUS_CONFIG_0 */
#define XPAR_PS7_IOP_BUS_CONFIG_0_S_AXI_BASEADDR 0xE0200000
#define XPAR_PS7_IOP_BUS_CONFIG_0_S_AXI_HIGHADDR 0xE0200FFF


/* Definitions for peripheral PS7_L2CACHEC_0 */
#define XPAR_PS7_L2CACHEC_0_S_AXI_BASEADDR 0xF8F02000
#define XPAR_PS7_L2CACHEC_0_S_AXI_HIGHADDR 0xF8F02FFF


/* Definitions for peripheral PS7_OCMC_0 */
#define XPAR_PS7_OCMC_0_S_AXI_BASEADDR 0xF800C000
#define XPAR_PS7_OCMC_0_S_AXI_HIGHADDR 0xF800CFFF


/* Definitions for peripheral PS7_PL310_0 */
#define XPAR_PS7_PL310_0_S_AXI_BASEADDR 0xF8F02000
#define XPAR_PS7_PL310_0_S_AXI_HIGHADDR 0xF8F02FFF


/* Definitions for peripheral PS7_PMU_0 */
#define XPAR_PS7_PMU_0_S_AXI_BASEADDR 0xF8891000
#define XPAR_PS7_PMU_0_S_AXI_HIGHADDR 0xF8891FFF
#define XPAR_PS7_PMU_0_PMU1_S_AXI_BASEADDR 0xF8893000
#define XPAR_PS7_PMU_0_PMU1_S_AXI_HIGHADDR 0xF8893FFF


/* Definitions for peripheral PS7_QSPI_LINEAR_0 */
#define XPAR_PS7_QSPI_LINEAR_0_S_AXI_BASEADDR 0xFC000000
#define XPAR_PS7_QSPI_LINEAR_0_S_AXI_HIGHADDR 0xFCFFFFFF


/* Definitions for peripheral PS7_RAM_0 */
#define XPAR_PS7_RAM_0_S_AXI_BASEADDR 0x00000000
#define XPAR_PS7_RAM_0_S_AXI_HIGHADDR 0x0003FFFF


/* Definitions for peripheral PS7_RAM_1 */
#define XPAR_PS7_RAM_1_S_AXI_BASEADDR 0xFFFC0000
#define XPAR_PS7_RAM_1_S_AXI_HIGHADDR 0xFFFFFFFF


/* Definitions for peripheral PS7_SCUC_0 */
#define XPAR_PS7_SCUC_0_S_AXI_BASEADDR 0xF8F00000
#define XPAR_PS7_SCUC_0_S_AXI_HIGHADDR 0xF8F000FC


/* Definitions for peripheral PS7_SLCR_0 */
#define XPAR_PS7_SLCR_0_S_AXI_BASEADDR 0xF8000000
#define XPAR_PS7_SLCR_0_S_AXI_HIGHADDR 0xF8000FFF


/* Definitions for peripheral ENDAT22_S_1 */
#define XPAR_ENDAT22_S_1_BASEADDR 0x43E00000
#define XPAR_ENDAT22_S_1_HIGHADDR 0x43E0FFFF


/******************************************************************/

/* Definitions for driver GPIO */
#define XPAR_XGPIO_NUM_INSTANCES 3

/* Definitions for peripheral AXI_GPIO_1 */
#define XPAR_AXI_GPIO_1_BASEADDR 0x41230000
#define XPAR_AXI_GPIO_1_HIGHADDR 0x4123FFFF
#define XPAR_AXI_GPIO_1_DEVICE_ID 0
#define XPAR_AXI_GPIO_1_INTERRUPT_PRESENT 0
#define XPAR_AXI_GPIO_1_IS_DUAL 0


/* Definitions for peripheral SIGNAL_IN */
#define XPAR_SIGNAL_IN_BASEADDR 0x41210000
#define XPAR_SIGNAL_IN_HIGHADDR 0x4121FFFF
#define XPAR_SIGNAL_IN_DEVICE_ID 1
#define XPAR_SIGNAL_IN_INTERRUPT_PRESENT 0
#define XPAR_SIGNAL_IN_IS_DUAL 1


/* Definitions for peripheral TESTLED */
#define XPAR_TESTLED_BASEADDR 0x41200000
#define XPAR_TESTLED_HIGHADDR 0x4120FFFF
#define XPAR_TESTLED_DEVICE_ID 2
#define XPAR_TESTLED_INTERRUPT_PRESENT 0
#define XPAR_TESTLED_IS_DUAL 0


/******************************************************************/

/* Canonical definitions for peripheral AXI_GPIO_1 */
#define XPAR_GPIO_0_BASEADDR 0x41230000
#define XPAR_GPIO_0_HIGHADDR 0x4123FFFF
#define XPAR_GPIO_0_DEVICE_ID XPAR_AXI_GPIO_1_DEVICE_ID
#define XPAR_GPIO_0_INTERRUPT_PRESENT 0
#define XPAR_GPIO_0_IS_DUAL 0

/* Canonical definitions for peripheral SIGNAL_IN */
#define XPAR_GPIO_1_BASEADDR 0x41210000
#define XPAR_GPIO_1_HIGHADDR 0x4121FFFF
#define XPAR_GPIO_1_DEVICE_ID XPAR_SIGNAL_IN_DEVICE_ID
#define XPAR_GPIO_1_INTERRUPT_PRESENT 0
#define XPAR_GPIO_1_IS_DUAL 1

/* Canonical definitions for peripheral TESTLED */
#define XPAR_GPIO_2_BASEADDR 0x41200000
#define XPAR_GPIO_2_HIGHADDR 0x4120FFFF
#define XPAR_GPIO_2_DEVICE_ID XPAR_TESTLED_DEVICE_ID
#define XPAR_GPIO_2_INTERRUPT_PRESENT 0
#define XPAR_GPIO_2_IS_DUAL 0


/******************************************************************/

/* Definitions for driver GPIOPS */
#define XPAR_XGPIOPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_GPIO_0 */
#define XPAR_PS7_GPIO_0_DEVICE_ID 0
#define XPAR_PS7_GPIO_0_BASEADDR 0xE000A000
#define XPAR_PS7_GPIO_0_HIGHADDR 0xE000AFFF


/******************************************************************/

/* Canonical definitions for peripheral PS7_GPIO_0 */
#define XPAR_XGPIOPS_0_DEVICE_ID XPAR_PS7_GPIO_0_DEVICE_ID
#define XPAR_XGPIOPS_0_BASEADDR 0xE000A000
#define XPAR_XGPIOPS_0_HIGHADDR 0xE000AFFF


/******************************************************************/

/* Definitions for driver INCREMENTAL_ENCODER_INTERFACE */
#define XPAR_INCREMENTAL_ENCODER_INTERFACE_NUM_INSTANCES 1

/* Definitions for peripheral ENCODER_INTERFACE */
#define XPAR_ENCODER_INTERFACE_DEVICE_ID 0
#define XPAR_ENCODER_INTERFACE_BASEADDR 0x43C70000
#define XPAR_ENCODER_INTERFACE_HIGHADDR 0x43C7FFFF
#define XPAR_ENCODER_INTERFACE_SPLB_CLK_PERIOD_PS 0
#define XPAR_ENCODER_INTERFACE_EDGE_CLOCK_TIMEOUT_TIME 100
#define XPAR_ENCODER_INTERFACE_CONFIG_REG_DEFAULT_VALUE 0x00000000
#define XPAR_ENCODER_INTERFACE_FILTER_HYSTERESIS_DEFAULT_VALUE 0x00000000


/******************************************************************/

/* Definitions for driver MULTIPLEXER */
#define XPAR_MULTIPLEXER_NUM_INSTANCES 1

/* Definitions for peripheral MULTIPLEXER_0 */
#define XPAR_MULTIPLEXER_0_DEVICE_ID 0
#define XPAR_MULTIPLEXER_0_S_AXI_BASEADDR 0x43DB0000
#define XPAR_MULTIPLEXER_0_S_AXI_HIGHADDR 0x43DBFFFF


/******************************************************************/

/* Definitions for driver PULSE_WIDTH_MODULATOR */
#define XPAR_PULSE_WIDTH_MODULATOR_NUM_INSTANCES 2

/* Definitions for peripheral CONVERTER_1_PWM */
#define XPAR_CONVERTER_1_PWM_DEVICE_ID 0
#define XPAR_CONVERTER_1_PWM_BASEADDR 0x43D60000
#define XPAR_CONVERTER_1_PWM_HIGHADDR 0x43D6FFFF
#define XPAR_CONVERTER_1_PWM_WIDTH_IN 16
#define XPAR_CONVERTER_1_PWM_NUMBER_OF_SIGNAL_SOURCES 1
#define XPAR_CONVERTER_1_PWM_HYSTERESIS_DEFAULT_VALUE 0
#define XPAR_CONVERTER_1_PWM_CARRIER_COUNTER_FRACTIONAL_BITS 10
#define XPAR_CONVERTER_1_PWM_CARRIER_INCREMENT_DEFAULT_VALUE 512
#define XPAR_CONVERTER_1_PWM_AMPLITUDE_DEFAULT_VALUE 2000
#define XPAR_CONVERTER_1_PWM_NUMBER_OF_CHANNELS 3
#define XPAR_CONVERTER_1_PWM_NUMBER_OF_CARRIERS 1
#define XPAR_CONVERTER_1_PWM_INTERRUPT_DIVISOR_WIDTH 8


/* Definitions for peripheral CONVERTER_2_PWM */
#define XPAR_CONVERTER_2_PWM_DEVICE_ID 1
#define XPAR_CONVERTER_2_PWM_BASEADDR 0x43CE0000
#define XPAR_CONVERTER_2_PWM_HIGHADDR 0x43CEFFFF
#define XPAR_CONVERTER_2_PWM_WIDTH_IN 16
#define XPAR_CONVERTER_2_PWM_NUMBER_OF_SIGNAL_SOURCES 1
#define XPAR_CONVERTER_2_PWM_HYSTERESIS_DEFAULT_VALUE 0
#define XPAR_CONVERTER_2_PWM_CARRIER_COUNTER_FRACTIONAL_BITS 10
#define XPAR_CONVERTER_2_PWM_CARRIER_INCREMENT_DEFAULT_VALUE 512
#define XPAR_CONVERTER_2_PWM_AMPLITUDE_DEFAULT_VALUE 2000
#define XPAR_CONVERTER_2_PWM_NUMBER_OF_CHANNELS 3
#define XPAR_CONVERTER_2_PWM_NUMBER_OF_CARRIERS 1
#define XPAR_CONVERTER_2_PWM_INTERRUPT_DIVISOR_WIDTH 8


/******************************************************************/

/* Definitions for driver QSPIPS */
#define XPAR_XQSPIPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_QSPI_0 */
#define XPAR_PS7_QSPI_0_DEVICE_ID 0
#define XPAR_PS7_QSPI_0_BASEADDR 0xE000D000
#define XPAR_PS7_QSPI_0_HIGHADDR 0xE000DFFF
#define XPAR_PS7_QSPI_0_QSPI_CLK_FREQ_HZ 200000000
#define XPAR_PS7_QSPI_0_QSPI_MODE 0
#define XPAR_PS7_QSPI_0_QSPI_BUS_WIDTH 2


/******************************************************************/

/* Canonical definitions for peripheral PS7_QSPI_0 */
#define XPAR_XQSPIPS_0_DEVICE_ID XPAR_PS7_QSPI_0_DEVICE_ID
#define XPAR_XQSPIPS_0_BASEADDR 0xE000D000
#define XPAR_XQSPIPS_0_HIGHADDR 0xE000DFFF
#define XPAR_XQSPIPS_0_QSPI_CLK_FREQ_HZ 200000000
#define XPAR_XQSPIPS_0_QSPI_MODE 0
#define XPAR_XQSPIPS_0_QSPI_BUS_WIDTH 2


/******************************************************************/

/* Definitions for driver REGISTER_ARRAY */
#define XPAR_REGISTER_ARRAY_NUM_INSTANCES 10

/* Definitions for peripheral CONVERTER_1_CURRENTREF */
#define XPAR_CONVERTER_1_CURRENTREF_DEVICE_ID 0
#define XPAR_CONVERTER_1_CURRENTREF_BASEADDR 0x43D10000
#define XPAR_CONVERTER_1_CURRENTREF_HIGHADDR 0x43D1FFFF
#define XPAR_CONVERTER_1_CURRENTREF_NUMBER_OF_REGISTERS 3
#define XPAR_CONVERTER_1_CURRENTREF_REGISTER_WIDTH 13
#define XPAR_CONVERTER_1_CURRENTREF_REG_SIGNED 1


/* Definitions for peripheral CONVERTER_1_MOVING_INTEGRAL_REG */
#define XPAR_CONVERTER_1_MOVING_INTEGRAL_REG_DEVICE_ID 1
#define XPAR_CONVERTER_1_MOVING_INTEGRAL_REG_BASEADDR 0x43D40000
#define XPAR_CONVERTER_1_MOVING_INTEGRAL_REG_HIGHADDR 0x43D4FFFF
#define XPAR_CONVERTER_1_MOVING_INTEGRAL_REG_NUMBER_OF_REGISTERS 8
#define XPAR_CONVERTER_1_MOVING_INTEGRAL_REG_REGISTER_WIDTH 24
#define XPAR_CONVERTER_1_MOVING_INTEGRAL_REG_REG_SIGNED 1


/* Definitions for peripheral CONVERTER_1_SYNCH_SAMPLING_REG */
#define XPAR_CONVERTER_1_SYNCH_SAMPLING_REG_DEVICE_ID 2
#define XPAR_CONVERTER_1_SYNCH_SAMPLING_REG_BASEADDR 0x43CF0000
#define XPAR_CONVERTER_1_SYNCH_SAMPLING_REG_HIGHADDR 0x43CFFFFF
#define XPAR_CONVERTER_1_SYNCH_SAMPLING_REG_NUMBER_OF_REGISTERS 4
#define XPAR_CONVERTER_1_SYNCH_SAMPLING_REG_REGISTER_WIDTH 13
#define XPAR_CONVERTER_1_SYNCH_SAMPLING_REG_REG_SIGNED 1


/* Definitions for peripheral CONVERTER_2_CURRENTREF */
#define XPAR_CONVERTER_2_CURRENTREF_DEVICE_ID 3
#define XPAR_CONVERTER_2_CURRENTREF_BASEADDR 0x43C90000
#define XPAR_CONVERTER_2_CURRENTREF_HIGHADDR 0x43C9FFFF
#define XPAR_CONVERTER_2_CURRENTREF_NUMBER_OF_REGISTERS 3
#define XPAR_CONVERTER_2_CURRENTREF_REGISTER_WIDTH 13
#define XPAR_CONVERTER_2_CURRENTREF_REG_SIGNED 1


/* Definitions for peripheral CONVERTER_2_MOVING_INTEGRAL_REG */
#define XPAR_CONVERTER_2_MOVING_INTEGRAL_REG_DEVICE_ID 4
#define XPAR_CONVERTER_2_MOVING_INTEGRAL_REG_BASEADDR 0x43CC0000
#define XPAR_CONVERTER_2_MOVING_INTEGRAL_REG_HIGHADDR 0x43CCFFFF
#define XPAR_CONVERTER_2_MOVING_INTEGRAL_REG_NUMBER_OF_REGISTERS 8
#define XPAR_CONVERTER_2_MOVING_INTEGRAL_REG_REGISTER_WIDTH 24
#define XPAR_CONVERTER_2_MOVING_INTEGRAL_REG_REG_SIGNED 1


/* Definitions for peripheral CONVERTER_2_SYNCH_SAMPLING_REG */
#define XPAR_CONVERTER_2_SYNCH_SAMPLING_REG_DEVICE_ID 5
#define XPAR_CONVERTER_2_SYNCH_SAMPLING_REG_BASEADDR 0x43C80000
#define XPAR_CONVERTER_2_SYNCH_SAMPLING_REG_HIGHADDR 0x43C8FFFF
#define XPAR_CONVERTER_2_SYNCH_SAMPLING_REG_NUMBER_OF_REGISTERS 4
#define XPAR_CONVERTER_2_SYNCH_SAMPLING_REG_REGISTER_WIDTH 13
#define XPAR_CONVERTER_2_SYNCH_SAMPLING_REG_REG_SIGNED 1


/* Definitions for peripheral REGISTER_EMU_INPUT */
#define XPAR_REGISTER_EMU_INPUT_DEVICE_ID 6
#define XPAR_REGISTER_EMU_INPUT_BASEADDR 0x43DF0000
#define XPAR_REGISTER_EMU_INPUT_HIGHADDR 0x43DFFFFF
#define XPAR_REGISTER_EMU_INPUT_NUMBER_OF_REGISTERS 1
#define XPAR_REGISTER_EMU_INPUT_REGISTER_WIDTH 14
#define XPAR_REGISTER_EMU_INPUT_REG_SIGNED 1


/* Definitions for peripheral REGISTER_EMU_OUT */
#define XPAR_REGISTER_EMU_OUT_DEVICE_ID 7
#define XPAR_REGISTER_EMU_OUT_BASEADDR 0x43DD0000
#define XPAR_REGISTER_EMU_OUT_HIGHADDR 0x43DDFFFF
#define XPAR_REGISTER_EMU_OUT_NUMBER_OF_REGISTERS 8
#define XPAR_REGISTER_EMU_OUT_REGISTER_WIDTH 13
#define XPAR_REGISTER_EMU_OUT_REG_SIGNED 1


/* Definitions for peripheral REGISTER_MUX_OUT */
#define XPAR_REGISTER_MUX_OUT_DEVICE_ID 8
#define XPAR_REGISTER_MUX_OUT_BASEADDR 0x43DE0000
#define XPAR_REGISTER_MUX_OUT_HIGHADDR 0x43DEFFFF
#define XPAR_REGISTER_MUX_OUT_NUMBER_OF_REGISTERS 8
#define XPAR_REGISTER_MUX_OUT_REGISTER_WIDTH 13
#define XPAR_REGISTER_MUX_OUT_REG_SIGNED 1


/* Definitions for peripheral RELAY */
#define XPAR_RELAY_DEVICE_ID 9
#define XPAR_RELAY_BASEADDR 0x43D00000
#define XPAR_RELAY_HIGHADDR 0x43D0FFFF
#define XPAR_RELAY_NUMBER_OF_REGISTERS 1
#define XPAR_RELAY_REGISTER_WIDTH 4
#define XPAR_RELAY_REG_SIGNED 0


/******************************************************************/

/* Definitions for Fabric interrupts connected to ps7_scugic_0 */
#define XPAR_FABRIC_CONVERTER_1_PWM_INTR_INTR 61U

/******************************************************************/

/* Canonical definitions for Fabric interrupts connected to ps7_scugic_0 */
#define XPAR_FABRIC_PULSE_WIDTH_MODULATOR_0_VEC_ID XPAR_FABRIC_CONVERTER_1_PWM_INTR_INTR

/******************************************************************/

/* Definitions for driver SCUGIC */
#define XPAR_XSCUGIC_NUM_INSTANCES 1U

/* Definitions for peripheral PS7_SCUGIC_0 */
#define XPAR_PS7_SCUGIC_0_DEVICE_ID 0U
#define XPAR_PS7_SCUGIC_0_BASEADDR 0xF8F00100U
#define XPAR_PS7_SCUGIC_0_HIGHADDR 0xF8F001FFU
#define XPAR_PS7_SCUGIC_0_DIST_BASEADDR 0xF8F01000U


/******************************************************************/

/* Canonical definitions for peripheral PS7_SCUGIC_0 */
#define XPAR_SCUGIC_0_DEVICE_ID 0U
#define XPAR_SCUGIC_0_CPU_BASEADDR 0xF8F00100U
#define XPAR_SCUGIC_0_CPU_HIGHADDR 0xF8F001FFU
#define XPAR_SCUGIC_0_DIST_BASEADDR 0xF8F01000U


/******************************************************************/

/* Definitions for driver SCUTIMER */
#define XPAR_XSCUTIMER_NUM_INSTANCES 1

/* Definitions for peripheral PS7_SCUTIMER_0 */
#define XPAR_PS7_SCUTIMER_0_DEVICE_ID 0
#define XPAR_PS7_SCUTIMER_0_BASEADDR 0xF8F00600
#define XPAR_PS7_SCUTIMER_0_HIGHADDR 0xF8F0061F


/******************************************************************/

/* Canonical definitions for peripheral PS7_SCUTIMER_0 */
#define XPAR_XSCUTIMER_0_DEVICE_ID XPAR_PS7_SCUTIMER_0_DEVICE_ID
#define XPAR_XSCUTIMER_0_BASEADDR 0xF8F00600
#define XPAR_XSCUTIMER_0_HIGHADDR 0xF8F0061F


/******************************************************************/

/* Definitions for driver SCUWDT */
#define XPAR_XSCUWDT_NUM_INSTANCES 1

/* Definitions for peripheral PS7_SCUWDT_0 */
#define XPAR_PS7_SCUWDT_0_DEVICE_ID 0
#define XPAR_PS7_SCUWDT_0_BASEADDR 0xF8F00620
#define XPAR_PS7_SCUWDT_0_HIGHADDR 0xF8F006FF


/******************************************************************/

/* Canonical definitions for peripheral PS7_SCUWDT_0 */
#define XPAR_SCUWDT_0_DEVICE_ID XPAR_PS7_SCUWDT_0_DEVICE_ID
#define XPAR_SCUWDT_0_BASEADDR 0xF8F00620
#define XPAR_SCUWDT_0_HIGHADDR 0xF8F006FF


/******************************************************************/

/* Definitions for driver SDPS */
#define XPAR_XSDPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_SD_1 */
#define XPAR_PS7_SD_1_DEVICE_ID 0
#define XPAR_PS7_SD_1_BASEADDR 0xE0101000
#define XPAR_PS7_SD_1_HIGHADDR 0xE0101FFF
#define XPAR_PS7_SD_1_SDIO_CLK_FREQ_HZ 25000000
#define XPAR_PS7_SD_1_HAS_CD 0
#define XPAR_PS7_SD_1_HAS_WP 0
#define XPAR_PS7_SD_1_BUS_WIDTH 0
#define XPAR_PS7_SD_1_MIO_BANK 0
#define XPAR_PS7_SD_1_HAS_EMIO 0


/******************************************************************/

#define XPAR_PS7_SD_1_IS_CACHE_COHERENT 0
/* Canonical definitions for peripheral PS7_SD_1 */
#define XPAR_XSDPS_0_DEVICE_ID XPAR_PS7_SD_1_DEVICE_ID
#define XPAR_XSDPS_0_BASEADDR 0xE0101000
#define XPAR_XSDPS_0_HIGHADDR 0xE0101FFF
#define XPAR_XSDPS_0_SDIO_CLK_FREQ_HZ 25000000
#define XPAR_XSDPS_0_HAS_CD 0
#define XPAR_XSDPS_0_HAS_WP 0
#define XPAR_XSDPS_0_BUS_WIDTH 0
#define XPAR_XSDPS_0_MIO_BANK 0
#define XPAR_XSDPS_0_HAS_EMIO 0
#define XPAR_XSDPS_0_IS_CACHE_COHERENT 0


/******************************************************************/

/* Definitions for driver SPIPS */
#define XPAR_XSPIPS_NUM_INSTANCES 2

/* Definitions for peripheral PS7_SPI_0 */
#define XPAR_PS7_SPI_0_DEVICE_ID 0
#define XPAR_PS7_SPI_0_BASEADDR 0xE0006000
#define XPAR_PS7_SPI_0_HIGHADDR 0xE0006FFF
#define XPAR_PS7_SPI_0_SPI_CLK_FREQ_HZ 166666672


/* Definitions for peripheral PS7_SPI_1 */
#define XPAR_PS7_SPI_1_DEVICE_ID 1
#define XPAR_PS7_SPI_1_BASEADDR 0xE0007000
#define XPAR_PS7_SPI_1_HIGHADDR 0xE0007FFF
#define XPAR_PS7_SPI_1_SPI_CLK_FREQ_HZ 166666672


/******************************************************************/

/* Canonical definitions for peripheral PS7_SPI_0 */
#define XPAR_XSPIPS_0_DEVICE_ID XPAR_PS7_SPI_0_DEVICE_ID
#define XPAR_XSPIPS_0_BASEADDR 0xE0006000
#define XPAR_XSPIPS_0_HIGHADDR 0xE0006FFF
#define XPAR_XSPIPS_0_SPI_CLK_FREQ_HZ 166666672

/* Canonical definitions for peripheral PS7_SPI_1 */
#define XPAR_XSPIPS_1_DEVICE_ID XPAR_PS7_SPI_1_DEVICE_ID
#define XPAR_XSPIPS_1_BASEADDR 0xE0007000
#define XPAR_XSPIPS_1_HIGHADDR 0xE0007FFF
#define XPAR_XSPIPS_1_SPI_CLK_FREQ_HZ 166666672


/******************************************************************/

/* Definitions for driver SWITCHING_EVENT_COUNTER */
#define XPAR_SWITCHING_EVENT_COUNTER_NUM_INSTANCES 2

/* Definitions for peripheral CONVERTER_1_SWITCHING_EVENT_COUNTER */
#define XPAR_CONVERTER_1_SWITCHING_EVENT_COUNTER_NUMBER_OF_CHANNELS 6
#define XPAR_CONVERTER_1_SWITCHING_EVENT_COUNTER_WIDTH_OUT 16
#define XPAR_CONVERTER_1_SWITCHING_EVENT_COUNTER_CHANNEL_NR_OUT 0
#define XPAR_CONVERTER_1_SWITCHING_EVENT_COUNTER_DEVICE_ID 0
#define XPAR_CONVERTER_1_SWITCHING_EVENT_COUNTER_BASEADDR 0x43D20000
#define XPAR_CONVERTER_1_SWITCHING_EVENT_COUNTER_HIGHADDR 0x43D2FFFF


/* Definitions for peripheral CONVERTER_2_SWITCHING_EVENT_COUNTER */
#define XPAR_CONVERTER_2_SWITCHING_EVENT_COUNTER_NUMBER_OF_CHANNELS 6
#define XPAR_CONVERTER_2_SWITCHING_EVENT_COUNTER_WIDTH_OUT 16
#define XPAR_CONVERTER_2_SWITCHING_EVENT_COUNTER_CHANNEL_NR_OUT 0
#define XPAR_CONVERTER_2_SWITCHING_EVENT_COUNTER_DEVICE_ID 1
#define XPAR_CONVERTER_2_SWITCHING_EVENT_COUNTER_BASEADDR 0x43CA0000
#define XPAR_CONVERTER_2_SWITCHING_EVENT_COUNTER_HIGHADDR 0x43CAFFFF


/******************************************************************/

/* Definitions for driver SYSMON */
#define XPAR_XSYSMON_NUM_INSTANCES 1U

/* Definitions for peripheral XADC_WIZ_0 */
#define XPAR_XADC_WIZ_0_IP_TYPE 0U
#define XPAR_XADC_WIZ_0_DEVICE_ID 0U
#define XPAR_XADC_WIZ_0_BASEADDR 0x43C30000U
#define XPAR_XADC_WIZ_0_HIGHADDR 0x43C3FFFFU
#define XPAR_XADC_WIZ_0_INCLUDE_INTR 1U


/******************************************************************/

/* Canonical definitions for peripheral XADC_WIZ_0 */
#define XPAR_SYSMON_0_IP_TYPE 0U
#define XPAR_SYSMON_0_DEVICE_ID XPAR_XADC_WIZ_0_DEVICE_ID
#define XPAR_SYSMON_0_BASEADDR 0x43C30000U
#define XPAR_SYSMON_0_HIGHADDR 0x43C3FFFFU
#define XPAR_SYSMON_0_INCLUDE_INTR 1U


/******************************************************************/

/* Definitions for driver TTCPS */
#define XPAR_XTTCPS_NUM_INSTANCES 3U

/* Definitions for peripheral PS7_TTC_0 */
#define XPAR_PS7_TTC_0_DEVICE_ID 0U
#define XPAR_PS7_TTC_0_BASEADDR 0XF8001000U
#define XPAR_PS7_TTC_0_TTC_CLK_FREQ_HZ 111111115U
#define XPAR_PS7_TTC_0_TTC_CLK_CLKSRC 0U
#define XPAR_PS7_TTC_1_DEVICE_ID 1U
#define XPAR_PS7_TTC_1_BASEADDR 0XF8001004U
#define XPAR_PS7_TTC_1_TTC_CLK_FREQ_HZ 111111115U
#define XPAR_PS7_TTC_1_TTC_CLK_CLKSRC 0U
#define XPAR_PS7_TTC_2_DEVICE_ID 2U
#define XPAR_PS7_TTC_2_BASEADDR 0XF8001008U
#define XPAR_PS7_TTC_2_TTC_CLK_FREQ_HZ 111111115U
#define XPAR_PS7_TTC_2_TTC_CLK_CLKSRC 0U


/******************************************************************/

/* Canonical definitions for peripheral PS7_TTC_0 */
#define XPAR_XTTCPS_0_DEVICE_ID XPAR_PS7_TTC_0_DEVICE_ID
#define XPAR_XTTCPS_0_BASEADDR 0xF8001000U
#define XPAR_XTTCPS_0_TTC_CLK_FREQ_HZ 111111115U
#define XPAR_XTTCPS_0_TTC_CLK_CLKSRC 0U

#define XPAR_XTTCPS_1_DEVICE_ID XPAR_PS7_TTC_1_DEVICE_ID
#define XPAR_XTTCPS_1_BASEADDR 0xF8001004U
#define XPAR_XTTCPS_1_TTC_CLK_FREQ_HZ 111111115U
#define XPAR_XTTCPS_1_TTC_CLK_CLKSRC 0U

#define XPAR_XTTCPS_2_DEVICE_ID XPAR_PS7_TTC_2_DEVICE_ID
#define XPAR_XTTCPS_2_BASEADDR 0xF8001008U
#define XPAR_XTTCPS_2_TTC_CLK_FREQ_HZ 111111115U
#define XPAR_XTTCPS_2_TTC_CLK_CLKSRC 0U


/******************************************************************/

/* Definitions for driver UARTPS */
#define XPAR_XUARTPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_UART_0 */
#define XPAR_PS7_UART_0_DEVICE_ID 0
#define XPAR_PS7_UART_0_BASEADDR 0xE0000000
#define XPAR_PS7_UART_0_HIGHADDR 0xE0000FFF
#define XPAR_PS7_UART_0_UART_CLK_FREQ_HZ 50000000
#define XPAR_PS7_UART_0_HAS_MODEM 0


/******************************************************************/

/* Canonical definitions for peripheral PS7_UART_0 */
#define XPAR_XUARTPS_0_DEVICE_ID XPAR_PS7_UART_0_DEVICE_ID
#define XPAR_XUARTPS_0_BASEADDR 0xE0000000
#define XPAR_XUARTPS_0_HIGHADDR 0xE0000FFF
#define XPAR_XUARTPS_0_UART_CLK_FREQ_HZ 50000000
#define XPAR_XUARTPS_0_HAS_MODEM 0


/******************************************************************/

/* Definitions for driver USBPS */
#define XPAR_XUSBPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_USB_0 */
#define XPAR_PS7_USB_0_DEVICE_ID 0
#define XPAR_PS7_USB_0_BASEADDR 0xE0002000
#define XPAR_PS7_USB_0_HIGHADDR 0xE0002FFF


/******************************************************************/

/* Canonical definitions for peripheral PS7_USB_0 */
#define XPAR_XUSBPS_0_DEVICE_ID XPAR_PS7_USB_0_DEVICE_ID
#define XPAR_XUSBPS_0_BASEADDR 0xE0002000
#define XPAR_XUSBPS_0_HIGHADDR 0xE0002FFF


/******************************************************************/

/* Definitions for driver XADCPS */
#define XPAR_XADCPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_XADC_0 */
#define XPAR_PS7_XADC_0_DEVICE_ID 0
#define XPAR_PS7_XADC_0_BASEADDR 0xF8007100
#define XPAR_PS7_XADC_0_HIGHADDR 0xF8007120


/******************************************************************/

/* Canonical definitions for peripheral PS7_XADC_0 */
#define XPAR_XADCPS_0_DEVICE_ID XPAR_PS7_XADC_0_DEVICE_ID
#define XPAR_XADCPS_0_BASEADDR 0xF8007100
#define XPAR_XADCPS_0_HIGHADDR 0xF8007120


/******************************************************************/

#endif  /* end of protection macro */
